M48
; DRILL file KiCad 10.0.5 date 2026-08-24T09:54:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-24T09:54:38+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X98.886Y-78.603
X99.013Y-105.654
T2
X102.008Y-91.388
T3
X100.0Y-68.0
X100.0Y-118.0
X180.0Y-68.0
X180.0Y-118.0
M30
