import json
from fault_model import Supervisor
from control_model import adc_code

def run(out):
    checked=[];trace=[]
    for sensors,fans in ((2,2),(2,1),(1,1)):
        label=f'{fans}F/{sensors}TH'
        cold=[adc_code(25)]*sensors;hot=[adc_code(50)]*sensors
        s=Supervisor(sensors,fans)
        for tick in range(101):
            result=s.update(tick/10,cold,[0]*fans)
            assert not result['alarm'] and result['duty']==[0.]*fans
        checked.append(label+': stopped fan/no tach does not alarm')
        for sensor in range(sensors):
            for fault in (0,1023):
                s=Supervisor(sensors,fans)
                for tick in range(81):
                    codes=cold.copy()
                    if tick<10:codes[sensor]=fault
                    result=s.update(tick/10,codes,[3]*fans)
                    assert result['sensor_fault']==(tick<60),(label,tick,result)
                    assert result['alarm']==(tick<60)
                    assert result['duty']==([1.]*fans if tick<60 else [0.]*fans)
                checked.append(f'{label}: sensor {sensor+1} code {fault}, immediate override, 5s recovery')
        for failed in range(fans):
            s=Supervisor(sensors,fans)
            for tick in range(111):
                pulses=[3]*fans
                if tick<40:pulses[failed]=0
                result=s.update(tick/10,hot,pulses)
                assert result['tach_fault'][failed]==(20<=tick<90),(label,tick,result)
                assert result['alarm']==(20<=tick<90)
                if result['alarm']:assert result['duty']==[1.]*fans
                if sensors==2 and fans==2:
                    trace.append({'time_s':tick/10,'missing_fan':failed+1,**result})
            checked.append(f'{label}: fan {failed+1} absent tach, 2s detection, 5s recovery')
        # A transient good sensor reading must not clear a persistent alarm.
        s=Supervisor(sensors,fans)
        for tick in range(71):
            codes=cold.copy()
            if tick==0 or tick==30:codes[0]=0
            result=s.update(tick/10,codes,[3]*fans)
            assert result['alarm']
        checked.append(label+': repeated sensor fault restarts recovery timer')
        # Mid-run loss, simultaneous loss and persistent alarm.
        s=Supervisor(sensors,fans)
        for tick in range(101):
            result=s.update(tick/10,hot,[3 if tick<30 else 0]*fans)
            assert result['alarm']==(tick>=49),(tick,result)
        checked.append(label+': mid-run/all-fan tach loss stays alarmed')
        # Brief missing pulses do not exceed timeout.
        s=Supervisor(sensors,fans)
        for tick in range(61):
            result=s.update(tick/10,hot,[0 if 20<=tick<30 else 3]*fans)
            assert not result['alarm']
        checked.append(label+': one-second tach interruption does not alarm')
    s=Supervisor()
    for tick in range(111):
        pulses=[0 if tick<30 or 50<=tick<60 else 3,3]
        result=s.update(tick/10,[adc_code(50)]*2,pulses)
        assert result['alarm']==(20<=tick<110),(tick,result)
    checked.append('2F/2TH: interrupted tach recovery restarts five-second timer')
    s=Supervisor()
    for args in ((0,[512],[0,0]),(0,[512,512],[-1,0]),(0,[1024,512],[0,0])):
        try:s.update(*args)
        except ValueError:pass
        else:raise AssertionError('Invalid input accepted')
    s.update(0,[512,512],[0,0])
    try:s.update(1,[512,512],[0,0])
    except ValueError:pass
    else:raise AssertionError('Unmodelled scheduling gap accepted')
    checked.append('Invalid ADC/count inputs and excessive scheduling gaps rejected')
    report={'status':'PASS: provisional supervisor assertions only','checks':checked,
            'timings_s':{'missing_tach':2,'sensor_recovery':5,'tach_recovery':5},
            'limits':['Tach counts are injected, not generated by a motor or MCU timer',
                      'Missing wire and stalled rotor cannot be distinguished',
                      'No RPM plausibility/noise rejection, watchdog or brownout recovery',
                      'No five-second startup scheduler implemented here',
                      'Full command cannot guarantee a stalled fan restarts',
                      'In-range sensor faults cannot be detected by near-rail checks']}
    (out/'fault_report.json').write_text(json.dumps(report,indent=2))
    (out/'fault_trace.json').write_text(json.dumps(trace,indent=2))
    return report
